### ISSUE TITLE
Not compatible with symfony console < 2.7

### ISSUE THREAD

**Issue by alekitto** [oradwell/covers-validator#14]
The `composer.json` file requires `"symfony/console": "^2.3 || ^3.0"`, but the command calls `addUsage` method that has been introduced in version 2.7.

**Comment by oradwell** [comment]
thanks for reporting this. I must have missed it. I will have a look and decide what to do about it.

**Comment by oradwell** [comment]
2.3 compatibility broken as of version 0.4.0. Instead of removing use of "addUsage" method I will change symfony console requirement to version 2.7.

**Comment by oradwell** [comment]
Fixed in releases [v0.5.1](https://github.com/oradwell/covers-validator/releases/tag/v0.5.1) and [v0.6.1](https://github.com/oradwell/covers-validator/releases/tag/v0.6.1)
