### ISSUE TITLE
Raise the memory_limit

### ISSUE THREAD

**Issue by ktomk** [oradwell/covers-validator#16]
Often in standard PHP configurations the memory_limit value is set to 128M. From tests I've seen covers-validator needs more.

In my case 512M was enough, but it's perhaps worth to add more. 

For example [composer raises internally to 1.5GB](https://github.com/composer/composer/blob/master/bin/composer#L23-L53).

I think something similar is a good addition to covers-validator.

/E: The quick fix for me is to set it from the outside:

    $ php -dmemory_limit=512M -f "$(which covers-validator)"

I think not needing this on first hand would make use/integration easier. Thanks for this working tool, I tried the other one you linked and I could only report issues w/o getting it to run.

**Comment by ktomk** [comment]
Alternatively one could parse the phpunit xml configuration if there is a `<php><ini ...>` setting for the memory limit and take over the value.

**Comment by oradwell** [comment]
@ktomk I personally think commands shouldn't change the environment they're running on. If your memory_limit value in your system is 128M you'd expect the command to stop running before it starts swapping and affecting other parts of your system.

Additionally if I add this change people with more tests will start asking for the limit to be raised to an even larger value.

I'll keep the PRs (#17, #18) and this issue to see if there are other people with this complaint.

**Comment by ktomk** [comment]
@oradwell: It's perhaps a misunderstanding, memory_limit is to be changed from a PHP script, it's changeable INI_ALL. If any of such ini settings are not to be changed, ini_set is deactivated. This is checked for in the PR.

**Comment by ktomk** [comment]
What is the minimum memory requirement of the utillity?

**Comment by oradwell** [comment]
@ktomk I don't think there is a minimum memory requirement. It depends on how big the project is. PHPUnit has the same issue. If you try to run the whole suite with a low memory limit setting it will fail. As you pointed out higher limit will not solve the issue for all projects.

**Comment by ktomk** [comment]
Question is what would be a sane default. I don't think the test-suite is that large where I have tested it and also I don't have the issue with phpunit as there is an ini setting in the phpunit.xml file in that project.

That is the alternative idea to extract the setting from there (as that configuration is taken into account anyway).

Would you see that (read out from phpunit.xml(.dist)) as applicable?

**Comment by oradwell** [comment]
I think 6000 tests are quite large. the project I have at work has 9000 tests and requires 512M of memory (around half the memory required to run full PHPUnit suite). When you run covers-validator on itself (26 tests) it can run with 8MB of memory.

**Comment by ktomk** [comment]
Then it's the testsuites class data which creates the memory appetite.
