### ISSUE TITLE
Provide a PHAR

### ISSUE THREAD

**Issue by theofidry** [oradwell/covers-validator#9]
Hi, nice tool thanks for it.

Would it be possible to get a phar instead of a composer dependency? Such tools are dedicated applications and you shouldn't have to add them to your project dependency (exactly as for phpunit and any static analysis tool).

Cheers

**Comment by oradwell** [comment]
Hi Theo, all releases come with a phar see them here: https://github.com/oradwell/covers-validator/releases

**Comment by theofidry** [comment]
Ah indeed, my bad I should have taken a look. It's just missing from the doc then :)

**Comment by oradwell** [comment]
ah, true I should add it to to the documentation.. thanks :+1:

**Comment by theofidry** [comment]
Ah, actually I get problems with it if both `covers-validator` and `phpunit` are installed as binaries:

```
Warning: include(phar:///path/to/my/project/bin/covers-validator/vendor/phpspec/prophecy/src/Prophecy/Prophet.php): failed to open stream: phar error: "vendor/phpspec/prophecy/src/Prophecy/Prophet.php" is not a file in phar "/path/to/my/project/bin/covers-validator" in phar:///path/to/my/project/bin/covers-validator/vendor/composer/ClassLoader.php on line 412
```

**Comment by oradwell** [comment]
I'll need to check and fix the PHAR. Did that error come up when you run `covers-validator` or `phpunit`?

**Comment by theofidry** [comment]
When running `covers-validator` on PHP7.0

**Comment by oradwell** [comment]
Hi Theo,

Just had a look at this. I used to use [box](https://github.com/box-project/box2) to build phars.
That had a lot of issues. I've just made another phar using phar-composer. It created a much bigger file hope it works for you.

Download it from here: [Release v0.4.0](https://github.com/oradwell/covers-validator/releases/tag/v0.4.0)
file named `covers-validator-full.phar`

Please confirm whether it's working.

Thanks
